name: Release artifact to npmjs.com
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - run: npm install
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
