name: Tests on PR
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          node-version: '16' # バージョンが低すぎるので今後の修正でバージョンを上げる
      - run: npm install
      - name: Type check
        run: tsc --noEmit
      - name: Build check
        run: webpack --config webpack.config.ts
